### ISSUE TITLE
Layout issue on episode detail view

### ISSUE THREAD

**Issue by remluben** [JeffreyWay/Laracasts-Bugs#104]
I've encountered a minor layout issue on Firefox 32.0 / Ubuntu 14.04. When watching an episode i.e. https://laracasts.com/series/build-a-laravel-app-from-scratch/episodes/20, the _completed_ button at the button row above the video container breaks the layout.

![dummy_users_and_statuses_-_2014-10-13_21 06 34](https://cloud.githubusercontent.com/assets/2439260/4618658/24eae9c6-530c-11e4-8db2-a6d34e73be88.png)

As far as I could see, the button width seems to be the problem:

``` css
 lesson-meta > li button {
     width: 147px;
 }
```

As I said, it's just a minor issue, that does not really effect my user experience at laracasts, but nevertheless, I thought I should give some feedback.

Thanks

**Comment by JeffreyWay** [comment]
Thanks. Fixed!
