### ISSUE TITLE
Feature Request(s): Continuous Playback, Playlists, Leanback mode, etc.

### ISSUE THREAD

**Issue by QWp6t** [JeffreyWay/Laracasts-Bugs#105]
I think it's a bit bold to refer to yourself as "Netflix for developers" when there isn't any kind of continuous playback. I was actually **very** disappointed when I realized the site doesn't have anything like that. It would be awesome if you could get that in there. It would also be cool if I could just start playing stuff in my "Watch Later" list and have it automagically go to the next lesson or series after completion.

For UX, I think it's important not to break out of fullscreen when switching to the next video for continuous playback. This is similar to how YouTube works, whereby videos in playlists will continue to play in fullscreen, and a new page load isn't actually triggered until the user exits fullscreen on her own.

As for Playlists and Leanback mode, that's not as important, obviously, but it would be nice to have at some point.

**Comment by QWp6t** [comment]
It just occurred to me that my tone might come across as demanding in those first few sentences. I was actually going for funny/playful/sarcastic and slightly overdramatic. I do in fact love Laracasts and am a yearly subscriber.

**Comment by thattomperson** [comment]
agreed
this is exactly what I came here to say

**Comment by GrandadEvans** [comment]
+1 :+1:  for the request. I actually have to download the videos to watch them in series. The downside of this is that the lessons don't come up as complete
