### ISSUE TITLE
Pagination (no results found) when searching via video tag

### ISSUE THREAD

**Issue by byfoz** [JeffreyWay/Laracasts-Bugs#111]
When visiting a page like https://laracasts.com/index/testing (via clicking a tag on a video), pagination appears at the bottom of the page.

Clicking one of the pages/next page button takes you to a page that returns no results, with URLs such as: https://laracasts.com/index/search/?page=2

**Comment by mattwells** [comment]
+1

**Comment by ChristopherDosin** [comment]
Same here

**Comment by gamerwalt** [comment]
+1

**Comment by byfoz** [comment]
Just checked this with the above example - after Jeffrey did the redesign it all looks like it is sorted.
