### ISSUE TITLE
can't play any video "the media could not be loaded,either because the server or network failed or because the format is not supported

### ISSUE THREAD

**Issue by ahhmarr** [JeffreyWay/Laracasts-Bugs#114]

**Comment by ahhmarr** [comment]
![selection_114](https://cloud.githubusercontent.com/assets/3134813/11556535/5c983280-99cd-11e5-8805-ac6a3b4886ca.png)

**Comment by skube** [comment]
I've been getting the same error intermittently all day today.

**Comment by ahhmarr** [comment]
well it was a DNS resolve issue for me
my ISP's dns was not able to open vimeo (the provider of the videos )
i changed it to the google one and it fixed it

**Comment by hulkur** [comment]
I still have this error pop up, but i found that if i press play before page is fully loaded (at around 80-90%) the video works fine.
