### ISSUE TITLE
Incorrect markdown parsing

### ISSUE THREAD

**Issue by zakiaziz** [JeffreyWay/Laracasts-Bugs#118]
I've asked a question here: https://laracasts.com/discuss/channels/general-discussion/wanted-feedback-on-architecture-for-an-automated-email-feature

The parsing for the markdown isn't what I'm expecting. Back ticks are being included in the code quotes, portions of code text is getting cut out, and underscores are concatenating commas?

Here is a gist of the exact same content: https://gist.github.com/zakiaziz/21c8f967587ccfb60e803d63682aa927

I've also attached a screenshot of what I'm seeing on the laracasts.com site:
![screen shot 2016-09-16 at 4 08 39 pm](https://cloud.githubusercontent.com/assets/940281/18600167/4be6c696-7c2a-11e6-9e0d-10159931ff1a.png)

**Comment by zakiaziz** [comment]
@JeffreyWay Also if you'd give your opinion on the matter I'd also be forever grateful 😃

**Comment by laracasts** [comment]
It's because I assume you have some text expander that converts apostrophes and ... into the fancy versions. That was messing up the parsing. I've fixed it for you. :)

**Comment by zakiaziz** [comment]
hmm, I don't have any text expander installed but it was probably something on my end. Thanks!
