### ISSUE TITLE
Bug: Duplicated Testimonial

### ISSUE THREAD

**Issue by nunomaduro** [JeffreyWay/Laracasts-Bugs#120]
Hey,

There is a duplicated testimonial at the end of the page:

<img width="949" alt="screenshot 2016-11-15 21 06 56" src="https://cloud.githubusercontent.com/assets/5457236/20322015/ce22f612-ab77-11e6-98a0-80ac2ceff75d.png">

**Comment by JeffreyWay** [comment]
Thanks! I just deleted the duplicate.
