### ISSUE TITLE
Bug: List date incorrect

### ISSUE THREAD

**Issue by nunomaduro** [JeffreyWay/Laracasts-Bugs#121]
Hey,

The first element of the list have an incorrect date. Because this should be chronological.

<img width="733" alt="screenshot 2016-11-16 20 38 35" src="https://cloud.githubusercontent.com/assets/5457236/20362655/b7047544-ac3c-11e6-992b-ba9e1e6b9bbd.png">

**Comment by JeffreyWay** [comment]
Thanks! Fixing this right now.
