### ISSUE TITLE
Cancel playing next video in series doesn't work

### ISSUE THREAD

**Issue by cvetan** [JeffreyWay/Laracasts-Bugs#126]
When you watch some video, video ends and you get suggestion to switch to next video or cancel. When you click cancel, it doesn't work but you are redirected to next video nevertheless. It worked before normally.

**Comment by JeffreyWay** [comment]
Fixed. Thanks.

**Comment by cvetan** [comment]
OK. But now if you let counter run up, it doesn't redirect you to next video. And it should. If i don't click anything process should go as indicated, when time runs out, go to next video.
