### ISSUE TITLE
Incorrect title text on the next-episode button

### ISSUE THREAD

**Issue by vintagesucks** [JeffreyWay/Laracasts-Bugs#129]
The title on the next-episode button incorrectly reads "Previous Episode".

@JeffreyWay Tagging you because I cannot tell if this repository is still active.

![grafik](https://user-images.githubusercontent.com/13335308/134443369-6a353858-eb74-492a-8aa6-fe7a4dab482e.png)
– https://laracasts.com/series/learn-vue-2-step-by-step/episodes/22

**Comment by JeffreyWay** [comment]
Thank you! I'm fixing that right now.
