### ISSUE TITLE
Better pagination / navigation perhaps

### ISSUE THREAD

**Issue by Faiyaz** [JeffreyWay/Laracasts-Bugs#13]
I am guessing this will change as the number of lessons increment. However, if thats not in the plan, I as a user would like to be able to move to the last page, without having to click next and manually travel all the way to the end and vice versa. 

And just a suggestion for usability purpose, it would be nice to be able to have an option to specify, how many results in one page, like 10, 15, 20 or all. Again, this is just a complete personal point of view, not a big deal. :)

**Comment by JeffreyWay** [comment]
Yeah, I can do that.
