### ISSUE TITLE
Laravel Path series stats counters are incorrect (or maybe static)

### ISSUE THREAD

**Issue by m0stwan1ed** [JeffreyWay/Laracasts-Bugs#132]
It is a little bit confusing to see, that the duration of the series is two times longer, than it was said on a "Path" page.

<img width="1104" alt="Снимок экрана 2023-01-31 в 18 30 38" src="https://user-images.githubusercontent.com/9297258/215838830-d466386b-4243-4aff-88ff-8b6cf72c9b88.png">

<img width="896" alt="Снимок экрана 2023-01-31 в 18 31 00" src="https://user-images.githubusercontent.com/9297258/215838801-486d5f30-f74e-4a5d-b1fe-c469dc78b310.png">

Im not complaining on length - it is awesome, when you can get more material, than expected. But still: it is a bug :-). Or maybe that counters on a "Path" page are just static.

**Comment by JeffreyWay** [comment]
Thank you. Just a caching issue. All fixed now.
