### ISSUE TITLE
Atom feed is reloading "old" lessons

### ISSUE THREAD

**Issue by gstjohn** [JeffreyWay/Laracasts-Bugs#14]
Hey Jeffrey,

Love the site and thought the best way to make sure I see all the new lessons is through my RSS reader, however, it is reloading "old" (to me) lessons.

Guessing it may have to do with one of a few things:
1. The unique id from all of your entries seems to be changing which will likely be identified as a new lesson by RSS readers. Currently, all IDs contain "2013-10-10" in the string which is today's date, but certainly most of these were published at a previous date.
2. Less likely, the atom:updated node should only be updated for "the most recent instant in time when an entry or feed was modified in a way the publisher considers significant" [link](http://tools.ietf.org/html/rfc4287#section-4.2.15). Currently, it seems to be time() which isn't necessarily accurate.

Hope this helps! Thanks again for all these great lesson!

**Comment by JeffreyWay** [comment]
I think that should be fixed now. 

https://laracasts.com/feed
