### ISSUE TITLE
Design Me a Better Welcome Page Banner

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/Laracasts-Bugs#16]
You know that red bubbles banner on the home page? I don't love it. But I'm not a designer.

https://www.laracasts.com/images/home-banner.jpg

Make me a better banner, and I'll give you a free membership to Laracasts. :)

Match the dimensions of the banner image, linked to above.

**Comment by msurguy** [comment]
You could use this service to create a cool looking banner :  
http://instacod.es/81498

=)

**Comment by codivist** [comment]
or you could use this one? :D 
![laracastsnewheader](https://f.cloud.github.com/assets/660284/1310250/a7047f94-31ed-11e3-8da8-3018bdf0e479.jpg)

It's at 100% quality so you can reduce if you want.  Or I can send you the psd.
The hue matches your link and button colors.

**Comment by JeffreyWay** [comment]
@codivist I like it, but I think Daryl might get mad at you. That's more his mascot than Laravel's, right?

**Comment by codivist** [comment]
Yeah that is more his mascot, I'm actually working on something more generic, but will look nice.

**Comment by JeffreyWay** [comment]
haha - I meant "mad at me" - not "mad at you." Looking forward to what you come up with!

**Comment by dschniepp** [comment]
First try: 
![background](https://f.cloud.github.com/assets/1108670/1310654/d76c2d92-31f4-11e3-8b21-51726e3950bb.png)
clean:
![2013-10-11 at 00 01](https://f.cloud.github.com/assets/1108670/1310771/a3b3338a-31f7-11e3-86e6-0fc780ebcf6f.png)
clean + chalkboard:
![2013-10-11 at 00 17_2](https://f.cloud.github.com/assets/1108670/1310869/3cb40350-31fa-11e3-85b5-b322dd5c5432.png)
![2013-10-11 at 00 17](https://f.cloud.github.com/assets/1108670/1310870/3cb48d34-31fa-11e3-8f6d-8ad690d66b4b.png)

@JeffreyWay do you stick to the colors of the website and logo?

edit: added two new banners

**Comment by JeffreyWay** [comment]
@dschniepp Looks good. 

Also going to add David's entry here, too.

http://davehe.mp/Wzim

Will choose one later tonight, when I get home to my main computer. :)

**Comment by codivist** [comment]
Just looked at David's and I swear I made mine before looking at his!  Really!
http://d.pr/i/djMK
http://d.pr/i/MGPl
http://d.pr/i/q33m

Thanks for providing an awesome place to learn!

**Comment by msurguy** [comment]
You could also use any of my wallpapers or parts of them : 
https://github.com/msurguy/Laravel-wallpapers

**Comment by msurguy** [comment]
![laracastslogo](https://f.cloud.github.com/assets/585833/1311315/612ba600-3206-11e3-9eef-653ec3886168.jpg)

Here's one

**Comment by JeffreyWay** [comment]
Okay, I've decided to go with David's entry for this first round. David, I'll contact you about your free account!

**Comment by codivist** [comment]
Congrats David!
