### ISSUE TITLE
Crashed after credit card info on signup

### ISSUE THREAD

**Issue by laur3d** [JeffreyWay/Laracasts-Bugs#17]
After completing the sign-up form, after submiting it it gave me the something went wrong screen. It seemed to work, because my account was created the the credit card was charged, but still from the ux point of view ... that is not nice at all, especially since this is a learning resource for building web stuff ...

**Comment by JeffreyWay** [comment]
That's odd. I'll check the logs. What's your username?

**Comment by laur3d** [comment]
Laur3d same as on github :)
