### ISSUE TITLE
Insecure content

### ISSUE THREAD

**Issue by BeingTomGreen** [JeffreyWay/Laracasts-Bugs#19]
Chrome is warning me about insecure content (relating to Vimeo), I get the following warnings:

`The page at https://laracasts.com/lessons/your-first-project-1 displayed insecure content from http://pdl.vimeocdn.com/05697/883/196289261.mp4?token2=1381503998_e87db279c1f10ffa7c955f2551b63706&aksessionid=d13f1bd842f1ce5d.`

`blocked] The page at https://player.vimeo.com/video/76655534 ran insecure content from http://player.vimeo.com/v2/receiver.html.`

**Comment by BeingTomGreen** [comment]
[Although it looks like it may not be fully supported at the minute!](http://vimeo.com/forums/help/topic:106549)

**Comment by JeffreyWay** [comment]
Yeah, hopefully, they'll be out of beta for that soon. Closing for now, as I can't do anything about it.
