### ISSUE TITLE
Next and previous arrows box in series not working properly 

### ISSUE THREAD

**Issue by salahaa1** [JeffreyWay/Laracasts-Bugs#28]
Only the text link inside the box is working, the whole box should be clickable ,
You could do this right away in your css file https://www.laracasts.com/css/min.css

.video-extras li {
float: left;
padding-bottom: 0;
margin-bottom: 0;
margin-left: 0.5em;
font-size: 1.4em;
border: 1px solid #E3E3E3 !important;
cursor: pointer;
}
.video-extras li a{
padding: 0.2em 0.7em;
display: block;
}

removed the padding from (.video-extras li )

**Comment by JeffreyWay** [comment]
All fixed. Thanks!
