### ISSUE TITLE
Some XSS

### ISSUE THREAD

**Issue by RobinMalfait** [JeffreyWay/Laracasts-Bugs#3]
## Hello!

I was trying to search and then I realised...

[XSS Problem](http://laracasts.com/search?q=%3Ca%20href=%22http://example.com/%22%20target=%22_blank%22%3EExample%3C/a%3E)

[Some CSS Fun Problems](http://laracasts.com/search?q=%3Cstyle%3Ebody%20{%20background-color:%20red;%20}%3C/style%3E)

(Actually I'm not sure if it is XSS; but You need to strip tags I think)

:)

**Comment by JeffreyWay** [comment]
All fixed (as noted on Twitter a while ago).
