### ISSUE TITLE
Gravatar image issue

### ISSUE THREAD

**Issue by TreverP** [JeffreyWay/Laracasts-Bugs#30]
It appears the site is trying to pull an image from gravatar.com for the email used. However, my gravatar image isn't being displayed for my laracast account image. I am betting this is because when I input my email address, during creating a laracast account, I used capital letters in the email. The problem is the md5 hash is case sensitive so to pull my image from gravatar.com is it expecting a hash of my email address, were my email address is all lowercase. 

Either way the image is displaying correctly in Laracast.com

**Comment by JeffreyWay** [comment]
Okay, this has been fixed. Thx!
