### ISSUE TITLE
Subscription end-date

### ISSUE THREAD

**Issue by toniperic** [JeffreyWay/Laracasts-Bugs#31]
I'd like to have in my Settings page shown when does my subscription ends.
All I have is a cancellation button and I'm unsure yet whether I'll subscribe for the next month or not, but I'm not quite sure when does it end anyways.

Thanks!

**Comment by henriquebim** [comment]
I also would like to have this. Will need to have my subscription canceled until this issue is fixed. 

I'm liking the tutorials, but I must know when my subscription will end so I can enjoy it fully without wasting money.

**Comment by JeffreyWay** [comment]
Added.
