### ISSUE TITLE
Request: Bookmarking and Code

### ISSUE THREAD

**Issue by Johnathan** [JeffreyWay/Laracasts-Bugs#32]
Not a bug or lesson suggestion so hoping it's ok here..

A way to bookmark or favourite lessons I want to watch or come back to would be great, the way it is on tutsplus.

Another thing that would be cool is including the code in the lesson description (only accessible by members obviously). The way railscasts do it is nice although it doesn't have to be a written tutorial, just code. That or pushing each lesson to gihub and including the link to that. It's much easier to watch the video then refer to text rather than skipping through the video multiple times.

**Comment by gvsrepins** [comment]
+1

**Comment by AMHOL** [comment]
+2

**Comment by JeffreyWay** [comment]
Done.
