### ISSUE TITLE
Logout out unexpectedly

### ISSUE THREAD

**Issue by blessingefkt** [JeffreyWay/Laracasts-Bugs#33]
I don't know if this is by design, but after I watch a video, I get logged out. If not immediately then a few minutes later.

**Comment by JeffreyWay** [comment]
Every single time? Or did this just happen once?

**Comment by blessingefkt** [comment]
It happens quite often, I'd say 90% of the time. Its usually after viewing a video, but sometimes I get logged out while browsing.

**Comment by dmfaux** [comment]
I seem to get logged out when selecting any links within the "more on Laracasts" section of the Disqus comment section

**Comment by isimmons** [comment]
I was getting this behavior when logging in without remember me checked.

**Comment by henriquebim** [comment]
I guess it's the same issue from #29 

You login at the non www domain, then Disqus redirect you to the www version (as noted by @dmfaux) and you have no session there.

**Comment by JeffreyWay** [comment]
Was fixed a bit ago.
