### ISSUE TITLE
Date on Series lessons

### ISSUE THREAD

**Issue by pechitook** [JeffreyWay/Laracasts-Bugs#38]
Maybe it is just a decision you took in order to keep the series timeless, so anyone can watch them and don't feel like they are old or outdated, but the problem I find is that I don't know whether a series was updated with new lessons or not. If I don´t remember the last lesson's title, there's no easy way to tell if I have seen it or not. Sure I can look into my history and search for it, but having the publish date is definitely easier. Or even maybe a NEW tag that lasts for a few days would help.

Anyone else feeling this way?

Thank you Jeff once again for this wonderful website.

**Comment by laracasts** [comment]
Yep, a "new" tag will be added soon. :)

**Comment by laracasts** [comment]
Okay, that's done. https://www.laracasts.com/series/laravel-from-scratch

**Comment by pechitook** [comment]
Great!
