### ISSUE TITLE
Video starts to replay in Firefox

### ISSUE THREAD

**Issue by scotthummel** [JeffreyWay/Laracasts-Bugs#40]
I've noticed two consistent bugs in Laracasts, both in Firefox.
1.  At the end of each video, the beginning of each video plays for a couple of seconds and then stops.  This happens consistently.
2.  If you start watching a video and then go off and do something else and then come back, the video gets buggy.  If you then click on the video (not the controls), the video locks your browser until the plug-in crashes.  I've been reporting the crashes, but the bug persists.  The bug doesn't happen if when you come back, you click on the controls.

**Comment by ahmedmahmoudit** [comment]
#### I have same problem:
- Here I can't start play videos ![FirefoxAurora version](https://cloud.githubusercontent.com/assets/721300/3278147/f03b6204-f3a8-11e3-9bd2-e09c85f69275.png)
- Here same proplem if you paused by click on controls and replay it will works but if you paused by click on video it will not replay you have to refresh the page -- chrome Version 35.0.1916.153
