### ISSUE TITLE
[Request] An option to save videos for later

### ISSUE THREAD

**Issue by johnmaguire** [JeffreyWay/Laracasts-Bugs#41]
Hey Jeffrey!

Just signed up and already loving the videos. I've been working with Laravel for the last month or so for a startup I'm working for and coming back to the PHP scene after a couple years I'm finding a lot has changed (in a positive way.) Your videos are a great guide for getting my code on track. :)

However, there's _so_ much material on your website that it's hard for me to remember everything I want to watch! It'd be awesome if you could add some small icon below videos that I can click to save videos, and then pull them up later.

Just an idea. :)

**Comment by JeffreyWay** [comment]
Forgot to update this thread - but this feature has been implemented now.
