### ISSUE TITLE
Using .row class on full width elements creates horizontal overflow

### ISSUE THREAD

**Issue by Gavrisimo** [JeffreyWay/Laracasts-Bugs#45]
So I've been looking at home page of laracasts.com and I noticed this horizontal overflow issue on my 15'' laptop.

It's happening because you are using `.row` class on elements that are essentially on my screen - full width.

It's elements right below these comments:

`<!-- RENAISSANCE -->`
`<!-- TESTIMONIALS -->`
`<!-- WHO AM I -->`

Just removing `.row` class fixes this issue and from what I saw there wasn't any glitch after that class was removed.

**Comment by JeffreyWay** [comment]
Sorry for taking so long to get back to you. Thanks for this! Fixed.
