### ISSUE TITLE
Expired subscription

### ISSUE THREAD

**Issue by losted** [JeffreyWay/Laracasts-Bugs#48]
Hello,

My credit card and laracast subscription expired around the same time. I wanted to watch an episode and obviously it said that I no longer had access. 

The first thing I'd like to point out is that I wasn't able to change my payment method. The only option I had available was "Reactivate subscription" but it isn't helpful since I need to use another card.

The second thing I'd like to point out is that I couldn't watch the video with the original player but I was able to click the download video button (the little cloud with a down arrow) and still watch the video!

Anyway.. thanks I guess!

**Comment by losted** [comment]
Quick fix thanks!

**Comment by laracasts** [comment]
:)
