### ISSUE TITLE
Demos and Folder Naming Syntax

### ISSUE THREAD

**Issue by markalanevans** [JeffreyWay/Laracasts-Bugs#5]
I noticed that in many of your demos, your creating folders Pascal Casing

MyNewClass

where as everything else in laravel is all lowercase

Do you have suggestions thoughts on this?

**Comment by JeffreyWay** [comment]
Not sure what you mean. Laravel core class names are pascal case, too.

**Comment by markalanevans** [comment]
https://laracasts.com/lessons/where-do-i-put-this  2:59 marker.

All of your directories are Pascal cased rather than lowercased.

Probably a good talk would be "The Larval Way" by Jeffrey Way ;)

Where you talk about: 
class / directory / file / method / variable 

naming conventions

![location php__html](https://f.cloud.github.com/assets/129052/1265329/30903478-2c6d-11e3-8088-5eb1be1be6ca.png)

Perhaps i should make that a "Request"?

**Comment by markalanevans** [comment]
Right, so whats the Logic for when it should be Pascal vs lowercased?

**Comment by JeffreyWay** [comment]
Oh, that's because those are vendor packages, installed through Composer. If you look at Laravel's core classes (like within the Auth folder you pointed to), they'll all be PascalCase.

**Comment by markalanevans** [comment]
Ok. Cool. So basically lowercase for generic directories.  Pascal for Package Directories.

Thank Jeffrey.
