### ISSUE TITLE
New videos accessible after expired subscription

### ISSUE THREAD

**Issue by sailorsteve** [JeffreyWay/Laracasts-Bugs#52]
I am still able to access the latest lessons (including today's) even though my subscription expired a few days ago. I am not complaining, but I don't believe this is the intended behavior.
Don't worry about my cancellation. I love the site and will be back in a few weeks.

**Comment by JeffreyWay** [comment]
Thanks! I'll take a look - though I think I just give a bit of padding before you officially lose access. I'll check, though. :)
