### ISSUE TITLE
Card declined notification & error updating details

### ISSUE THREAD

**Issue by BeingTomGreen** [JeffreyWay/Laracasts-Bugs#53]
My card had expired and I had forgotten to update the details with Laracasts.

Ideally there'd be an email or a notification on the site because I didn't know until I tried to watch a video.

I then tried to amend my details, but got a "Whoops, looks like something went wrong." error on https://laracasts.com/subscriptions/{id}.

**Comment by bmadigan** [comment]
If I could also add, that the CVV number is required on the Update Credit Card form. In Canada, we have Debit cards that can be used just like a Credit Card but they do not have CVV numbers so I get an error :-(
