### ISSUE TITLE
/settings is a broken URL

### ISSUE THREAD

**Issue by ciarand** [JeffreyWay/Laracasts-Bugs#56]
The welcome email has the following:

> # Welcome to Laracasts!
> 
> Yay, thanks so much for signing up! Please note that your provided credit
> card has been charged, according to the subscription plan that you chose.
> 
> So what are you waiting for? Get to it! Your free copy of Laravel Testing
> Decoded may be downloaded from your **settings** page. Also, don't forget that
> the site will frequently be updated. Check back often!
> 
> \- Jeffrey

The bolded "settings" text links to `/settings`, which is an invalid destination.

I also can't see the download link on the admin page, although I may just be
missing it.

**Comment by laracasts** [comment]
Fixed! (Emailed you about the book.)

**Comment by ciarand** [comment]
Thanks!
