### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by IsraelOrtuno** [JeffreyWay/Laracasts-Bugs#57]
Not really a bug... What about get notified by e-mail when a new video is posted?

**Comment by juukie** [comment]
I mostly check the Twitter account or browse the website on 'Whats new'. If this feature would be added, each user should be able to turn it off.

**Comment by TreverP** [comment]
I think this would be a little redundant as Jeffery is releasing a new video pretty much daily. I believe the only days I have not seen videos posted are over the weekend.

**Comment by JeffreyWay** [comment]
This is done. You can enable it from your profile settings page.

https://laracasts.com/admin/profile
