### ISSUE TITLE
Viewing History: Incorrect stats

### ISSUE THREAD

**Issue by zslabs** [JeffreyWay/Laracasts-Bugs#62]
Hi,
On https://laracasts.com/admin/history I think it's a bit confusing with how it's currently set up. If I visit https://laracasts.com/lessons/vagrant-and-sequel-pro for example, but don't watch the video (maybe I'm just reading the comments), it still counts (and says "Watched lesson: Vagrant and Sequel Pro").

I think it'd make more sense to use a callback function from [their API](http://developer.vimeo.com/player/js-api) to record a "video view" rather than a "page view". Thanks!

**Comment by ghost** [comment]
+1
