### ISSUE TITLE
Unwatched lessons text

### ISSUE THREAD

**Issue by stoppert** [JeffreyWay/Laracasts-Bugs#65]
Not having any unwatched videos shows a filler text that seems more appropriate for the "watched" videos page (possibly just copied over?)

![unwatched](https://f.cloud.github.com/assets/1810949/1861632/33f0ded0-77c5-11e3-8a06-e61c2407f01c.JPG)

**Comment by bbashy** [comment]
Was going to report this too, still there and I read it every time thinking "that doesn't make sense Jeffrey!"
