### ISSUE TITLE
Subscription / Billing issue

### ISSUE THREAD

**Issue by grayxr** [JeffreyWay/Laracasts-Bugs#69]
Jeffrey, I'm sorry -  I didn't know at the time but it seems that I had access to all videos during the month of December when I wasn't billed for that month - I had an issue with a debit card around that time and I got a new card so my subscription was deactivated - though I thought it was reactivated shortly after. I logged in recently on a different device and saw that my subscription was deactivated - so I reactivated it. Would you like me to just send you $9 for the month of December?

**Comment by JeffreyWay** [comment]
Sorry for the delay. No worries.
