### ISSUE TITLE
Nice Words Here, Please

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/Laracasts-Bugs#7]
Hi -

If you're a supporter of Laracasts, and are willing to have your comment + gravatar on the home page of the site, I'd appreciate a short 1-2 endorsement. :)

You can leave it in this thread, as comment.

**Comment by RobinMalfait** [comment]
Laracasts is just awesome, the perfect place to learn the best framework in the world! I love it!

**Comment by rkosinski** [comment]
Jeffrey Way is the best guide in Laravel world! Thank you for Laracasts.

**Comment by tobysteward** [comment]
Laracasts goes much further than the numerous books out there can. It puts a real-time perspective on building Laravel applications and offers a chance to pair-program with a real expert.

**Comment by lori** [comment]
A great way to learn Laravel from a great teacher! Doubles as a video reference manual :)

**Comment by mohitmamoria** [comment]
Stop wasting your money. Buy Jeffrey lunch once a month instead. Laracasts goes much beyond a regular course on a framework. It makes you an awesome developer - an Artisan!

**Comment by alesanabriav7** [comment]
the next level for learning laravel!

**Comment by dayaki** [comment]
What other way to learn laravel, than to watch one of the best in the field hold your hands and teach you to see the beauty in the framework.

**Comment by schmeits** [comment]
This is just awesome, I keep checking the website for new updates every day :)  Great job Jeffrey :+1:

**Comment by drfraker** [comment]
Of all the ways to learn Laravel, this is by far the best. From beginner to pro, you will pick up a ton.

**Comment by orphanedrecord** [comment]
The PHP community is doing good things.

**Comment by Fuhrmann** [comment]
The best resource to learn Laravel! Jeffrey did an amazing job. This was exactly what was missing for the community Laravel grow further.

**Comment by dexbarrett** [comment]
The ins and outs of a great framework explained by a great teacher - that´s what Laracasts is.

**Comment by ghost** [comment]
Laracasts was the missing piece in learning Laravel. Yeah there were some series on other websites but none of those were at this level. Laracasts + available books out there took me from a total newb level to a decent level. 
So Jeffrey … THANK YOU ! 
For giving me  the chance to learn this amazing framework !
I'll keep buying you lunch many many months from now on

**Comment by unknownArtist** [comment]
In Laracasts videos, It really feels comfortable listening Jeffrey voice and the way he teaches the concepts of PHP and Laravel is awesome. Hats off for good work and the monthly subscription is nothing for these quality videos.

**Comment by joedawson** [comment]
I recently stumbled upon Laravel just a couple of weeks ago. I'll admit, I've struggled with understanding the framework, especially since I haven't used a framework prior to Laravel. Thanks to Jeffrey at Laracasts, I'm converting my current projects into Laravel with absolute ease.

**Comment by megawubs** [comment]
Thanks Jeffrey for learning me PHP and Laravel!

**Comment by joecohens** [comment]
Laracast it's simply the best learning source for Laravel and PHP!

**Comment by mykebates** [comment]
Laracasts is pure gold and is exactly what the community needed.  Not only do you gain excellent Laravel knowledge but Jeffrey's tutorials give insight into advanced topics that transcend into many programming languages.

**Comment by spamoom** [comment]
Great resource by Jeffrey Way to take my knowledge of Laravel to the limits!

**Comment by noeldiaz** [comment]
The best way to learn the ins and outs of the Laravel Framework.  Really helps take it to the next level.  You can't beat learning while watching, especially with such a good and detailed instructor.  Two thumbs way up!

**Comment by tolu360** [comment]
Laravel is arguably the most beautiful and comprehensive modern PHP framework out of the box! Jeffrey is simply a one-of-a-kind tutor, teaching is obviously his calling. Laravel and Laracasts, twice as nice!!

**Comment by nullcitizen** [comment]
If it wasn't for Jeffrey Way I wouldn't be half the developer I am today. Laracasts is the resource the Laravel community has been waiting for to take us all to the next level.

**Comment by Gufran** [comment]
Laracast is the third best thing that happened to Laravel, after Taylor and Jeffery!

**Comment by MamunHoque** [comment]
I am already learn many important thing on Laracast..  Laracast resources really helpful for Laravel lover. everyday i checked for new tutorial :) +1:

**Comment by Josh-Bruce** [comment]
Laracasts is a breath of fresh air in a sea of confusion and when it comes to learning online, Jeffrey Way is one of the best!

**Comment by abhishekkhaware** [comment]
Laracast is really a great place for visual learning. Taylor Otwell and Jeffrey Way creating a very powerful and  Restful Web resource for Web Development.

Thanks ^Jeffrey Way And Taylor Otwell.

**Comment by mj-watts** [comment]
Not only will you become better at developing with this amazing framework Jeffrey will teach you to become a better developer all round. He is in my opinion one of the best and most encouraging teachers out there.

**Comment by junedomingo** [comment]
This is my first time to use Framework and I choose Laravel,.  It has awesome community and easy to learn. you want to know more? why don't you visit Laracasts.com

**Comment by sdebacker** [comment]
Hope to loose weight as I eat one lunch less per month. Thanks.

**Comment by sineld** [comment]
So many useful information about Laravel. Thanks @jeffreyway

**Comment by davidstanley01** [comment]
Great resource for learning to use an awesome framework. Thanks Jeffrey!

**Comment by ghost** [comment]
At this rate, Jeffrey won't be paying for lunch ever again. And quite rightly - thanks for this @JeffreyWay!

**Comment by JeffreyWay** [comment]
Thanks for these, everyone! I've added the first dozen, and will continue updating the /testimonials page.

https://www.laracasts.com/testimonials

**Comment by bgallagh3r** [comment]
It doesn't matter if you're a beginner or an expert, there's something for everyone here.  It not only makes a great learning tool, but it is an amazing resource of information!

**Comment by wikichua** [comment]
you made me in love with php and laravel again

**Comment by michaeldeol** [comment]
Laracasts offer a phenomenal way to learn the Laravel framework. Highly recommended!

**Comment by henryjuan** [comment]
Laracasts 是一條學習 Laravel 的捷徑。

**Comment by tambijalouqa** [comment]
just signed up. Laracasts is a fountain that keeps giving. Jeffery rocks!

**Comment by pacuna** [comment]
Laracasts is taking my software development skills to the next level!. Welcome to the new era of learning.

**Comment by philpalmieri** [comment]
Laracasts is awesome - I bought a subscription on the company card, and now (im sure against some terms of condition somewhere) our small office is watching them as a team daily

**Comment by 6ber6ou** [comment]
Laracasts is "The Place to Go" for all of use how wants to mastering Laravel.
Thanks to Jeffrey Way I am now a real Laracasts Addict !

**Comment by mrgodhani** [comment]
Great tutorials on best practices and learning a new framework ! After watching it I can now really see big difference  transferring to Laravel from Codeigniter.

**Comment by sergigp** [comment]
The best 6€ I've ever spend.

**Comment by mdurao** [comment]
Learning anything should be always like this... a pleasure.
Thank you for helping me through the learning process of such a great framework.

**Comment by whoisandy** [comment]
Having something like Laracasts was the missing piece in the laravel ecosystem. I've been following Jeffrey for a long time ! All I say is if you want to really master the framework, forget about the $9 and just get started. I promise you will never worry again ! Great work Jeffrey !

**Comment by edi9999** [comment]
Jeffrey is the best coding teacher I ever had. He knows what to explain in a very clear way. <3

**Comment by dbpolito** [comment]
Loving the Laracasts content so far, this is pretty simple to newcomers and also good to learn new stuff...

**Comment by Ardakilic** [comment]
Loving the content so far, Jeffrey and his tutorials are one of the reasons I can code like this today (since CodeIgniter times). I'm glad I subscribed to Laracasts.

**Comment by jasperkooij** [comment]
I'm excited to learn more about Laravel and Jeffrey is doing an excellent job in demonstrating

**Comment by Sprocket** [comment]
Absolutely love the site. Jeffery is one of the best screencasters out there. Subscription is a no-brainer!

**Comment by sachittandukar** [comment]
Laravel made PHP interesting again... Jeffrey and Laracast made programming on Laravel enjoyable again...

**Comment by toniperic** [comment]
I just scratched the surface of Laravel watching Jeffrey Way's tutorials. By far the best tutor there is!

**Comment by kristjaningi** [comment]
Jeffrey Way is probably the best tutor I have ever watched. He took my Laravel skills to the next level.

**Comment by Nunomneto** [comment]
Laracasts should be the template for all other Tech Training websites out there. The quality of the work and effort that goes into each screencast from Beginner level to advanced it is impressive and of outstanding quality. Please continue with your hard work, commitment and passion and I won't be alone when I say that it is a pleasure to pay you lunch once a month when in return I can benefit of your fantastic work.

**Comment by adamgoose** [comment]
Laracasts doesn't just tell you how to do something, it tells you why it works! Great for everyone, from novice to expert!

**Comment by nbourguig** [comment]
"The best way to learn for Artisans"

**Comment by pedrommone** [comment]
I'm from Brazil and I could understand every single screencast!

**Comment by brenelz** [comment]
Been following Jeffrey's work from nettuts to laracasts and there is no visual teacher as concise and knowledgeable as him.

**Comment by jtgrimes** [comment]
I've dug into half the Laravel framework files and have had pull requests accepted into the framework.  I consider myself pretty expert at Laravel and I learn something from nearly _every_ Laracast video.

**Comment by gstjohn** [comment]
For the "show-and-tell" learner, there's no better, more affordable way to get up to speed with Laravel, dev tools, or coding best practices than Laracast.

**Comment by orphanedrecord** [comment]
Laracasts is the Single Responsibility Principle for Laravel tutorials! Dedicating short amounts of time more often, rather than several hours at once, is a great way to learn without feeling overwhelmed. Jeffrey Way is able to break complex topics into interesting bite-sized pieces that are fun to digest!

**Comment by msurguy** [comment]
I am the original owner of Laracasts.com domain and my purpose for it was to make #1 learning resource for Laravel community. While I have not found the time to do make it by myself, I knew that Jeffrey would exceed all of my expectations and that's exactly what happened. I am now a subscriber myself and the company where I work also bought a subscription after I demo-ed it to them. Love the content!

**Comment by mrobit** [comment]
Simply put, Laracasts has expanded my knowledge of development by steering me in the right direction to learn more on my own in addition to learning from the screencasts.

**Comment by Leenug** [comment]
Laracasts is hands down the best resource available for picking up laravel from scratch as well as catching tips and tricks you might have otherwise missed.

**Comment by rgomezcasas** [comment]
Jeffrey is simply the teacher I never had, and Laracast is the subject I ever dreamed to course.

**Comment by thefuzzy0ne** [comment]
Utterly addictive and enjoyable. I think I might have my first ever man-crush...

**Comment by ashishkumar** [comment]
Laracasts is really useful and improving my understanding of core MVC concepts. Even though being a college student means I can’t afford the monthly fee, the free lessons that you’ve provided are pretty rad! Thanks for not having everything behind a paywall.

**Comment by sergiotirado** [comment]
Laracasts is the quickest and cheapest way to find out what Laravel is all about. Get ready to be impressed.

**Comment by lewiswharf** [comment]
Laracasts makes my code look good.

**Comment by santiagogg** [comment]
Simpler and clearer.. .the best Jeffrey Way to learn Laravel

**Comment by mohitmamoria** [comment]
Jeffrey && Laracasts == Laravel++

**Comment by mikerogne** [comment]
Laracasts is the definitive resource for learning Laravel. Period.

**Comment by abhishekkhaware** [comment]
Learn the goodness of LARAVEL with New Skill at  Laracasts. Jeffrey Way will Help You.

-- Thanks To Laracasts and Jeffrey Way.

**Comment by mikefrancis** [comment]
Never got to 88mph, stuck in the present and can't go back to the future, so while I'm here I'm watching Jeffrey's Laracasts.

**Comment by iMarkCampbell** [comment]
Probably, the best mentor I'll never meet!

**Comment by JeffreyWay** [comment]
Thank you, everyone! I've begun adding these quotes to the site.

Looks like a lot of 5-minute hugs will be given out. :)

**Comment by tomschlick** [comment]
As someone converting a fairly large SaaS app from another framework to Laravel, I have found Laracasts to be invaluable. I will be recommending it to any future developers we bring onto our team.

**Comment by mhanson01** [comment]
Laracasts is a must have for all Laravel developers.

**Comment by hettiger** [comment]
Buy him the lunch, he has deserved it!
