### ISSUE TITLE
 Update Credit Card Details Error

### ISSUE THREAD

**Issue by carlosflorencio** [JeffreyWay/Laracasts-Bugs#70]
Show's an error when updating: "Whoops, looks like something went wrong.".

**Comment by markovic131** [comment]
Same problem here. Tried 3 different valid cards but same error reported.

**Comment by fedeisas** [comment]
@JeffreyWay same problem here: "Your card does not support this type of purchase."

My bank changed my CCs, and I successfully updated all my online payments except yours. Please check it out: I miss your screencasts.

Thanks!

**Comment by fedeisas** [comment]
@JeffreyWay My bank was messing around. I talked to them and now it works!

**Comment by JeffreyWay** [comment]
@fedeisas Oh good. Thanks for letting me know!

**Comment by BobbyBorisov** [comment]
@JeffreyWay i have the same problem like @fedeisas ("Your card does not support this type of purchase."). Do you experience such problems from other people? I have to call the bank but i guess nothing has changed because i'm using it everywhere

**Comment by kilamieaz** [comment]
@JeffreyWay i have the same problem "Your card does not support this type of purchase." ?
