### ISSUE TITLE
Episodes scheduled for later dates show up in What's New?

### ISSUE THREAD

**Issue by kreitje** [JeffreyWay/Laracasts-Bugs#73]
![screen shot 2014-01-25 at 12 42 37 pm](https://f.cloud.github.com/assets/603228/2002494/e66e70e0-85f8-11e3-8c2c-98257e631ea7.png)
![screen shot 2014-01-25 at 12 42 30 pm](https://f.cloud.github.com/assets/603228/2002495/e7aace04-85f8-11e3-93e3-ba19f6e0a745.png)

**Comment by laracasts** [comment]
Fixed. :)
