### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by vrave** [JeffreyWay/Laracasts-Bugs#74]
This is not really a bug but more likely a nuisance to new people who are trying to learn your tutorials. Every time that I try to copy or imitate the tutorial I'm watching I always stumble with minor glitches, due to the fact that we have different version of dependecies.

So if I may suggest or request, please put a composer.json file on the prerequisite of every tutorial that way I know which version to install from composer.

e.g In your file manipulation tutorial, I was following everything that you've typed and said until I hit a roadblock where my intervention doesnt work. I've just found out that I'm using the latest version of it and you weren't and there was quite big of a difference. Some functions from that video were deprecated from the newer version. 

Therefore, I believe that putting a composer.json file before starting the tutorial will help us to be on the same page as you.

**Comment by bbashy** [comment]
It's always best to use the latest (since things change), just work out what's wrong and adjust it to what he's doing. Works out for the better.

**Comment by JeffreyWay** [comment]
Yeah - it's a valid concern. I need to figure how to best deal with that.

As a rule, though, I'm always using the latest version of the framework.

**Comment by vrave** [comment]
Thanks for the reply. But thanks to this problem I've learned some valuable lessons too. Now I've actually started reading documentations which helps me to solve my previous issues. But going back to the problem. I've just realized that you can also start your videos by either stating your current package's versions or maybe put a link or a readme file that contains the version you are using during the time of the recording.
