### ISSUE TITLE
Favorited lessons

### ISSUE THREAD

**Issue by nickromanenko** [JeffreyWay/Laracasts-Bugs#76]
When I'm on https://laracasts.com/lessons and clicking on 'Favorited', I'm getting 500 Internal Server error and "Whoops, looks like something went wrong." message in case I have no favorited lessons. It works fine if I have favorited lessons.
It would be nicer to display some friendly message, that I don't have favorited messages instead of an error.

**Comment by laracasts** [comment]
Fixed! Sorry - little regression from the other day.
