### ISSUE TITLE
Titles of the lessons are messing up the layout

### ISSUE THREAD

**Issue by scrubmx** [JeffreyWay/Laracasts-Bugs#78]
I think this could be solved with a simple CSS trick

Make the h3 tag of the titles truncate the text and show an ellipsis like [this](http://i.imgur.com/DLyF5Mw.png)

```
h3{
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

Maybe show the entire title on hover?

```
h3:hover{
    white-space: normal;
}
```

**Comment by JeffreyWay** [comment]
This has been resolved with the most recent design iteration. Thx.
