### ISSUE TITLE
Lesson Player container

### ISSUE THREAD

**Issue by joedawson** [JeffreyWay/Laracasts-Bugs#8]
Not sure if this is intentional, but IMO it doesn't look right (see circled). Minor, I know - but details :)

![alt text](http://f.cl.ly/items/2I2x3Q362L2M2x310J05/Screen%20Shot%202013-10-05%20at%2017.15.28.png)

**Comment by JeffreyWay** [comment]
Whoops. Good eye. Fixed now. :)
