### ISSUE TITLE
Watched & unwatched feature seems not to work

### ISSUE THREAD

**Issue by michaelgrossklos** [JeffreyWay/Laracasts-Bugs#81]
If I klick on the link "watched", there's no video listed but I have watched a lot the last couple of days. The opposite on the "unwatched" link. There are all Videos listed. Furthermore the checklist is completely unchecked -> "don't know if this should be automatically checked by watching a video but I guess it should"

**Comment by imade-nl** [comment]
Yep, I've the same problem.

**Comment by michaelgrossklos** [comment]
As I found out, there is no automation for that. You have to click a checkbox underneath the video or in the small teaser box. 

http://swlf.de/jing/2014-02-13_1447.png
http://swlf.de/jing/2014-02-13_1447-1.png
