### ISSUE TITLE
/lessons vs /lessons?page=1 after Featured Video feature.

### ISSUE THREAD

**Issue by lildwitte** [JeffreyWay/Laracasts-Bugs#82]
If you load the /lessons route without the page attribute it doesn't load the featured video with the tiled results below.

While if you load the /lessons?page=1 version it loads the featured video (currently the PHPSpec video) in the tiled results below.

**Comment by laracasts** [comment]
Hmm - it seems to be doing that for me. Maybe a caching issue?
