### ISSUE TITLE
[Design "issue"] Title to large

### ISSUE THREAD

**Issue by michaelgrossklos** [JeffreyWay/Laracasts-Bugs#87]
It's not a huge issue. It is a ui feeling-ish thing. In my opinion the top title on the video page is a little bit to high, because I always have to scroll down to reach the video controls. I think it would be much better if people don't has to scroll to watch the videos, because if you watch several videos, you always has to scroll and it becomes very annoying.  

http://f2w.me/2014-02-26_0308.png

**Comment by JeffreyWay** [comment]
I'll be reducing it slightly. Thanks for this.
