### ISSUE TITLE
Become a better developer with Laracasts

### ISSUE THREAD

**Issue by mj-watts** [JeffreyWay/Laracasts-Bugs#9]
Not only will you become better at developing with this amazing framework Jeffrey will teach you to become a better developer all round. He is in my opinion one of the best and most encouraging teachers out there.

**Comment by mj-watts** [comment]
Sorry iphone version of site confused me and posted in wrong section!  Please delete

**Comment by JeffreyWay** [comment]
No problem. Added to the site. Thanks! :)
