### ISSUE TITLE
Testimonials, Please!

### ISSUE THREAD

**Issue by JeffreyWay** [JeffreyWay/Laracasts-Bugs#90]
Hi, all - 

If you're a happy member of Laracasts, and would like to have your face and website URL linked to from the Laracasts home page (and testimonials area), I'd be incredibly appreciative if you'd leave a 1-2 sentence testimonial in this thread.

http://laracasts.com/testimonials

**Comment by ToddSmithSalter** [comment]
"Laracasts has not only improved my understanding of Laravel as a framework, but the language, constructs, and best practices of PHP development. Highly recommended."

Todd Smith-Salter - todd@centerdrive.ca

**Comment by adamgoose** [comment]
I'm learning something new at Laracasts every day! It's a phenomenal way to incrementally grow your development strategy!

Adam Engebretson - adam@enge.me

**Comment by imjakechapman** [comment]
The one thing I really appreciate about Laracasts is that Jeffrey has content for developers of all knowledge levels. From setting up Laravel for the first time to going deep into the Laravel IOC to Laravel testing and deployment, Laracasts has it all. I always learn something new whenever I login and watch a video.

Jake Chapman - jake@imjakechapman.com

**Comment by dreamtime** [comment]
Laracasts has been an absolutely amazing resource in learning Laravel as well as learning more solid coding practices in general. Jeffrey has a unique ability to clearly and concisely break down complicated topics so anyone can grasp them and apply them in their own projects.

**Comment by csoutham** [comment]
Love Laracasts! It let's me explore areas of Laravel outside of my comfort zone. Not only that Jeffrey likes to try loads of different methods to getting to the same result which helps understand why you end up where you are. Plus he's great at explaining pretty complex functionality! Thank you :+1:
Chris Southam - me@csoutham.com

**Comment by BastianHofmann** [comment]
"I can't stop refreshing!"
- Bastian Hofmann https://twitter.com/HofmannBastian

**Comment by mhanson01** [comment]
Laracasts has dramatically helped level up my PHP code.  Jeffrey Way knows exactly how to break down advanced topics so they are not overwhelming, but actually enjoyable to learn!

Mark Hanson - http://mhanson01.com

**Comment by lstables** [comment]
Laracasts is awesome I check everyday for new lessons. Jeff is a legend!

www.infinety.co.uk

**Comment by jocahdj** [comment]
Jeffrey was born to be a teacher! Every topic gets covered in great detail and its a pleasure to learn from somebody how loves what he does!

Jovan Haji-Djurich
http://app.pianotechnique.org/

**Comment by kbirmhrjn** [comment]
Laracasts a day discover new things everyday.

**Comment by driesvints** [comment]
"Probably the most _must-watch_, web development screencasts on the internet."

Dries Vints
http://driesvints.com

**Comment by donaldallen** [comment]
"Laracasts has made me a better developer."

Don Allen
http://donaldallen.com/

**Comment by thepsion5** [comment]
Laracasts provide invaluable insight into features of Laravel that might not be in my comfort zone.In addition, his incremental style of teaching is a great aid in understanding complex framework-agnostic topics and design patterns. It'd be a worthy investment at five times the price.

Sean Mumford
http://www.seanmumford.com

**Comment by udiudi** [comment]
Jeffrey is a great developer and teacher. Laracasts, without a doubt, is an amazing resource to become a better developer and in-depth understanding of Laravel.

Udi Mosayev
http://udiudi.com

(feel free to edit, my English isn't great)

**Comment by bbashy** [comment]
Came to Laracasts knowing almost nothing about Laravel, after a month I had made a full blogging system, learnt more about configuring tools to help me develop on my Mac and I'm now working on a full featured site using what I've learnt from Jeffrey and his videos!

Ben Sampson
https://bashy.im

**Comment by Dixens** [comment]
I use Laracasts daily and always learn a lot - about Laravel but also about best practices of PHP development. Jeffrey is by far the most talented dev teacher online.

Nicolas Dupuy
www.dixens.net

**Comment by gmann1982** [comment]
I have been a member since day one and it's the best tool not only for Laravel but for so much more. Jeffrey is one of the best tutors online. 

George Rome

**Comment by freekmurze** [comment]
Better than breakfast!

Freek
spatie.be

**Comment by jmshal** [comment]
"Laracasts renewed my excitement in PHP. It's rare to find such a great community that is committed to teaching, sharing and socialising. It's an honour to be taught by such an awesome guy! Do not waste this amazing opportunity!"

Jacob Marshall
http://jacobmarshall.co

**Comment by JeffreyWay** [comment]
Thanks so much, everyone! I've just added these to the testimonials page. They'll show up in the next day or so, once the cache resets. :)

**Comment by mohamedallam1991** [comment]
If you ever want to learn Laravel or its ecosystem ......you gonna love it, well in my case you become addicted to learn with Jeffrey!

http://www.mohamedallam.org/
