### ISSUE TITLE
Favorited button doesn't update upon clicking

### ISSUE THREAD

**Issue by TreverP** [JeffreyWay/Laracasts-Bugs#91]
When clicking 'Not Favorited' or 'Favorited' button the ajax doesn't appear to be working correctly. The heart icon toggles color however the text doesn't update until a page refresh.

**Comment by JeffreyWay** [comment]
What browser and OS do you use?

**Comment by martindilling** [comment]
It's the same for me, the icon updates but not the text. :)

Chrome/Win7 64bit

**Comment by JeffreyWay** [comment]
Ahh - it's updating. Just haven't changed the text. If you reload, it'll update. Will swap out text soon.

**Comment by TreverP** [comment]
I have seen this on Chrome & FF for windows and Chrome & Safari for Mac OS X

**Comment by TreverP** [comment]
Correct the icon updates but not the test until a page refresh
