### ISSUE TITLE
Reactivation does not work

### ISSUE THREAD

**Issue by terion-name** [JeffreyWay/Laracasts-Bugs#93]
I go to https://laracasts.com/admin/subscription/reactivate, hit reactivation button, page reloads and nothing happens

**Comment by JeffreyWay** [comment]
You get no response at all? Would you mind trying again, just in case it was an anomaly?

**Comment by jhotujec** [comment]
I doesn't work for me either. Same problem. Already tried multiple times.

**Comment by Amegatron** [comment]
The same for me. Auto-prolonging didn't work in Feb becuase I had no money on my card, since then I was unable to reactivate subscription. I tried multiple times as in Feb, and as now.

**Comment by laracasts** [comment]
I'm going to dig into this over the weekend. It seems to be an isolated thing that only affects a small number of people. So I'll figure that out, and update this thread.
