### ISSUE TITLE
Why I was deactivated?

### ISSUE THREAD

**Issue by terion-name** [JeffreyWay/Laracasts-Bugs#94]
My next payment should be at 17th March (previous was 17th Feb, all this data is shown in https://laracasts.com/admin/subscription/payments), but my acount is deactivated. Moreover, reactivation doesn't work (see #93 ticket)

**Comment by JeffreyWay** [comment]
Looks like your card was denied. It may need a new credit card, which you can do from your settings page.

**Comment by terion-name** [comment]
I've update credit card info, it charged money and reactivated account.
But I still don't understand, why my account was deactivated two weeks earlier before next scheduled payment
