### ISSUE TITLE
<li> style type on series Pags

### ISSUE THREAD

**Issue by gmsantos** [JeffreyWay/Laracasts-Bugs#95]
In series page (https://laracasts.com/series) the `list-style-type` are not set as `none`.

![Series Page](https://f.cloud.github.com/assets/1991286/2359644/1fb760be-a61a-11e3-8c4d-a6bc78332440.PNG)

Using Firefox 27 @ Windows XP

**Comment by JeffreyWay** [comment]
Thanks - weird that's on Firefox. Fixed! :)
