### ISSUE TITLE
Player stopped working

### ISSUE THREAD

**Issue by ghost** [JeffreyWay/Laracasts-Bugs#99]
I can't neither to view nor to download any lesson.

**Comment by ghost** [comment]
It looks like the problem is on Vimeo's side or misconfiguration issue.
The browser sends GET http://player.vimeo.com/external/XXXXXXXX.hd.mp4?s=... and doesn't receive any reply.

**Comment by ghost** [comment]
That's for sure odd vimeo banning issue. I was able to get underlying mp4 via server in Western Europe.
Please fix this discrimination.

**Comment by JeffreyWay** [comment]
I'm looking into it right now. It's entirely related to Vimeo. I haven't applied any viewing restrictions, of course. Hopefully, I'll hear back from them soon.

**Comment by ghost** [comment]
Vimeo fixed the bug. https://vimeo.com/forums/help/topic:116084
